add jar /home/data/elasticsearch-hadoop-2.3.0/dist/elasticsearch-hadoop-2.3.0.jar;
add jar /usr/hdp/2.4.0.0-169/hive/lib/commons-httpclient-3.0.1.jar;

use cas;
drop table vdwh_pol_es;

create external table vdwh_pol_es (
pol_num               string ,
pol_stat_cd           string ,
bill_day              double ,
mode_prem             double ,
lyr_mpre              double ,
div_bal               double ,
bill_mthd             string ,
pmt_mode              string ,
grp_no                string ,
div_opt               string ,
pd_to_dt              string ,
pol_reiss_dt          string ,
ipo_ind               string ,
iio_ind               string ,
iio_percentage        double ,
pol_trmn_dt           string ,
uwg_clas              string ,
prem_paid_total       double ,
db_opt                string ,
no_of_coverage        double ,
source_of_business    string ,
crcy_code             string ,
pol_app_dt            string ,
pol_iss_dt            string ,
pol_eff_dt            string ,
orig_pol_eff_dt       string ,
par_code              string ,
no_lapse_gurt_ind     string ,
auto_rebal_opt        string ,
mpre                  double ,
paid_up_add           double ,
oyt_amt               double ,
rcc_ind               string ,
mortality             string ,
open_flag             string ,
coll_bank             string ,
prc_ind               string ,
line_of_bus           string ,
sngl_prem_ind         string ,
pdf_bal               double ,
pdf_rate              double ,
prod_cat              string ,
plan_code_base        string ,
vers_num_base         string ,
sa_cd_2               string ,
wa_cd_1               string ,
wa_cd_2               string ,
gurt_bnft             double ,
gurt_amt              double ,
life_incm             double ,
rmn_gurt_amt          double ,
rmn_life_incm         double ,
anty_opt              string ,
anty_freq             double ,
anty_ref_dt           string ,
anty_payo_amt         double ,
dist_chnl_cd          string ,
owner_type            string ,
inf_yr                string ,
inf_mth               string ,
rpc_ind               string ,
payor_dth_dt          string ,
chnl_ind              string ,
morbidity             string ,
owner_nationality     string ,
insured_nationality   string ,
owner_res_city        string ,
insured_res_city      string ,
owner_id_doc_typ      string ,
insured_id_doc_typ    string ,
special_clas          string ,
agt_code              string ,
convrt_fr_pol         string ,
mvy_ded_to_dt         string ,
reins_mthd            string ,
bill_to_dt            string , 
pt_susp              double 
)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.nodes' = 'nn1', 'es.resource' = 'data/cas.vdwh_pol');

insert into vdwh_pol_es select * from vdwh_pol;

use stg;
drop table policy_master_es;
create external table policy_master_es (
 eff_frm_dt            string,
 eff_to_dt             string,
 pol_id                string,
 plan_id               string,
 pol_stat_cd           string,
 line_of_bus           string,
 plan_code             string,
 vers_num              string,
 prod_cat              string,
 crcy_code             string,
 pol_app_dt            string,
 pol_iss_dt            string,
 pol_eff_dt            string,
 pd_to_dt              string,
 pol_reiss_dt          string,
 pol_trmn_dt           string,
 orig_pol_eff_dt       string,
 bill_to_dt            string,
 mvy_ded_to_dt         string,
 agt_code              string,
 mode_prem             double,
 lyr_mpre              double,
 mpre                  double,
 bill_mthd             string,
 pmt_mode              string,
 bill_day              double,
 db_opt                string,
 div_bal               double,
 prem_paid_total       double,
 pdf_bal               double,
 pdf_rate              double,
 grp_no                string,
 div_opt               string,
 ipo_ind               string,
 iio_ind               string,
 iio_percentage        double,
 uwg_clas              string,
 no_of_coverage        double,
 source_of_business    string,
 par_code              string,
 no_lapse_gurt_ind     string,
 auto_rebal_opt        string,
 paid_up_add           double,
 oyt_amt               double,
 rcc_ind               string,
 mortality             string,
 open_flag             string,
 coll_bank             string,
 sngl_prem_ind         string,
 sa_cd_2               string,
 wa_cd_1               string,
 wa_cd_2               string,
 dist_chnl_cd          string,
 inf_yr                string,
 inf_mth               string,
 rpc_ind               string,
 payor_dth_dt          string,
 chnl_ind              string,
 morbidity             string,
 owner_type            string,
 owner_nationality     string,
 insured_nationality   string,
 owner_res_city        string,
 insured_res_city      string,
 owner_id_doc_typ      string,
 insured_id_doc_typ    string,
 prc_ind               string,
 special_clas          string,
 convrt_fr_pol         string,
 reins_mthd            string,
 pmt_susp              double,
 gurt_bnft             double,
 gurt_amt              double,
 life_incm             double,
 rmn_gurt_amt          double,
 rmn_life_incm         double,
 anty_opt              string,
 anty_freq             double,
 anty_ref_dt           string,
 anty_payo_amt         double,
 sys_cd                string,
 ref_contract_no       string,
 ref_cert_no           string,
 active_status         string,
 batch_dt              string,
 last_upd_tms          string
 )
 STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.nodes' = 'nn1', 'es.resource' = 'data/stg.pol_master');

insert into policy_master_es select * from policy_master;
